added detect-movement example project
allthingstalk/arduino-lorawan-sdk pull request #2
Opened 2022-02-16 23:04 UTC by edihasaj

link from my github source  https://github.com/edihasaj/detect-moevement-lorawan

2022-02-16 23:05 UTC, edihasaj commented
it is tested and it is working. Maybe you can contribute by adding an image in the readme section.

2022-03-29 08:59 UTC, epiller commented
Hey @edihasaj, thanks for contributing! There are a few things that would need to be addressed first before merging this. I'll comment them in the code but it boils down to:  
There's no need to use the delay() function - in its current state, the example can take up to 200 seconds to react and send data after an event has happened. Instead, by adding an interrupt (or simply reading the PIR pin every second), you could make it send data only if an event happens. This would save battery life, improve response and send less payloads if there's no movement.

2022-03-29 09:14 UTC, epiller requested changes

2022-03-29 09:14 UTC, epiller commented on examples/Rapid Development Kit/detect-movement/detect-movement.ino
> +  sendSensorValues();
This should be removed and called from the readSensors function instead

2022-03-29 09:14 UTC, epiller commented on examples/Rapid Development Kit/detect-movement/detect-movement.ino
> +  delay(sendEvery*1000);
This should be moved from here into readSensors function as well, but with a 1 second delay only

2022-03-29 09:14 UTC, epiller commented on examples/Rapid Development Kit/detect-movement/detect-movement.ino
> +void readSensors() {                                    // Name of our function that we'll call from the loop function below
Would be cool if it sends data if something happens. Something like this:

```
pirValue = analogRead(PIRSensPin);
if (pirValue != previousPirValue) {
  if (pirValue) {
    debugSerial.println("Motion detected!");
  } else {
    debugSerial.println("Motion expired.");
  }
  sendSensorValues();
  previousPirValue = pirValue;
}
```

You'd just need to define a global variable ```previousPirValue```.

2022-03-30 07:35 UTC, edihasaj reviewed
added changes, check if everything is as excepted. Thank you for your time.

2022-09-14 13:00 UTC, merged